

// renderer process


export interface BrickInfo {
    health: number;
    color?: string;
}

export const lvl_1: Array<Array<BrickInfo>> = [
    [
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
    ],
    [
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
        { health: 0 },
    ],
    [
        { health: 0 },
        { health: 0 },
        { health: 2, color: 'gray' },
        { health: 2, color: 'gray' },
        { health: 2, color: 'gray' },
        { health: 2, color: 'gray' },
        { health: 2, color: 'gray' },
        { health: 2, color: 'gray' },
        { health: 2, color: 'gray' },
        { health: 2, color: 'gray' },
        { health: 0 },
        { health: 0 },
    ],
    [
        { health: 0 },
        { health: 0 },
        { health: 1, color: 'red' },
        { health: 1, color: 'red' },
        { health: 1, color: 'red' },
        { health: 1, color: 'red' },
        { health: 1, color: 'red' },
        { health: 1, color: 'red' },
        { health: 1, color: 'red' },
        { health: 1, color: 'red' },
        { health: 0 },
        { health: 0 },
    ],
    [
        { health: 0 },
        { health: 0 },
        { health: 1, color: 'green' },
        { health: 1, color: 'green' },
        { health: 1, color: 'green' },
        { health: 1, color: 'green' },
        { health: 1, color: 'green' },
        { health: 1, color: 'green' },
        { health: 1, color: 'green' },
        { health: 1, color: 'green' },
        { health: 0 },
        { health: 0 },
    ],
    [
        { health: 0 },
        { health: 0 },
        { health: 1, color: 'blue' },
        { health: 1, color: 'blue' },
        { health: 1, color: 'blue' },
        { health: 1, color: 'blue' },
        { health: 1, color: 'blue' },
        { health: 1, color: 'blue' },
        { health: 1, color: 'blue' },
        { health: 1, color: 'blue' },
        { health: 0 },
        { health: 0 },
    ],
    [
        { health: 0 },
        { health: 0 },
        { health: 1, color: 'orange' },
        { health: 1, color: 'orange' },
        { health: 1, color: 'orange' },
        { health: 1, color: 'orange' },
        { health: 1, color: 'orange' },
        { health: 1, color: 'orange' },
        { health: 1, color: 'orange' },
        { health: 1, color: 'orange' },
        { health: 0 },
        { health: 0 },
    ],
];
  
